export const QUERY_KEYS = {
  register: "register",
  login: "login",
  logout: "logout",
  plans: "plans",
  planById: "planById",
  subscribe: "subscribe",
  cancelSubscription: "cancelSubscription",
  me: "me",
  analyticsPosts: "analyticsPosts",
  analyticsReels: "analyticsReels",
  analyticsPerformances: "analyticsPerformances",
  audienceByGender: "audienceByGender",
  audienceByAge: "audienceByAge",
  audienceByCountries: "audienceByCountries",
  audienceByCities: "audienceByCities",
  innerAnalyticsPosts: "innerAnalyticsPosts",
  innerAnalyticsReels: "innerAnalyticsReels",
  innerAnalyticsPerformances: "innerAnalyticsPerformances",
  innerAudienceByGender: "innerAudienceByGender",
  innerAudienceByAge: "innerAudienceByAge",
  innerAudienceByCountries: "innerAudienceByCountries",
  innerAudienceByCities: "innerAudienceByCities",
};
